### ISSUE TITLE
graphconncomp() 函数

### ISSUE THREAD

**Issue by YyHEAN** [zht639/SFMC#1]
在coclustering bipartite fast1.m这个代码的188行，
[clusternum,y]=graphconncomp(SS0);
其中的graphconncomp() 函数并没有给出定义
请问如何解决这个问题

**Comment by zht639** [comment]
我不是作者，我只是个搬运工，源文件在百度网盘，我只是把它搬到GitHub上了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月20日(周三) 下午2:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [zht639/SFMC] graphconncomp() 函数 (Issue #1)




 
在coclustering bipartite fast1.m这个代码的188行，
 [clusternum,y]=graphconncomp(SS0);
 其中的graphconncomp() 函数并没有给出定义
 请问如何解决这个问题

**Comment by YyHEAN** [comment]
好的，谢谢
